name: cpp-linter

on:
  push:
    paths:
      - "docs/examples/demo/*"
  pull_request:
    paths:
      - "docs/examples/demo/*"

permissions: {}

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - uses: cpp-linter/cpp-linter-action@0b93f5833680005fbb233652d0e3d8835b3cc2f3  # main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          thread-comments: false

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        env:
          CHECKS_FAILED: ${{ steps.linter.outputs.checks-failed }}
        run: |
          echo "some linter checks failed. $CHECKS_FAILED"
        # for actual deployment
        # run: exit 1
