name: MkDocs Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  build-docs:
    uses: cpp-linter/.github/.github/workflows/mkdocs.yml@2343264e1cf33bc688e01d962323d5cb70fe1905  # main
