name: Release Drafter

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  draft-release:
    permissions:
      contents: write
      pull-requests: read
    uses: cpp-linter/.github/.github/workflows/release-drafter.yml@2343264e1cf33bc688e01d962323d5cb70fe1905  # main
