name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
permissions: {}

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: cpp-linter/.github/.github/workflows/stale.yml@f3f3c766170cc625ccc900fcec546bff75d2e0f0 # main
